### ISSUE TITLE
Multiple JS Calls in multiple context

### ISSUE THREAD

**Issue by ayunawani** [ericwlange/AndroidJSCore#52]
Hi,

I am getting the following error on performing multiple js method calls in multiple context 
Any idea why this error is coming?

Thanks ,
Ayush Nawani

```
E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
java.util.concurrent.TimeoutException: org.liquidplayer.webkit.javascriptcore.JSObject.finalize() timed out after 10 seconds
                                                                  at org.liquidplayer.webkit.javascriptcore.JSContext$JSContextWorker$SyncRunnable.block(JSContext.java:100)
                                                                  at org.liquidplayer.webkit.javascriptcore.JSContext$JSContextWorker.sync(JSContext.java:113)
                                                                  at org.liquidplayer.webkit.javascriptcore.JSContext.sync(JSContext.java:124)
                                                                  at org.liquidplayer.webkit.javascriptcore.JSObject.finalize(JSObject.java:312)
                                                                  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                  at java.lang.Thread.run(Thread.java:818)
```

**Comment by ericwlange** [comment]
Please upgrade to [LiquidCore](https://github.com/LiquidPlayer/LiquidCore).  This issue has been resolved there, and AndroidJSCore is currently unsupported.
