### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Array.prototype')

### ISSUE THREAD

**Issue by badboy-tian** [ericwlange/AndroidJSCore#53]
```
TypeError: undefined is not an object (evaluating 'Array.prototype')
                                                                  at org.liquidplayer.webkit.javascriptcore.JSContext.evaluateScript(JSContext.java:267)
                                                                  at org.liquidplayer.webkit.javascriptcore.JSContext.evaluateScript(JSContext.java:290)
                                                                  at com.i7play.rts.activity.SplashActivity$initData$2.run(SplashActivity.kt:54)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
```

here is my js file:
```
tags.forEach(function(tag) {
  Node.prototype[tag] = function _tagMethod() {
    var state = this._baseState;
    var args = Array.prototype.slice.call(arguments);

    assert(state.tag === null);
    state.tag = tag;

    this._useArgs(args);

    return this;
  };
});
```

**Comment by ericwlange** [comment]
AndroidJSCore is no longer supported.  Please use [`LiquidCore`](https://github.com/LiquidPlayer/LiquidCore/wiki/LiquidCore-as-a-Native-Javascript-Engine) instead.  AndroidJSCore is based on an older version of WebKit.

**Comment by tianqiujie** [comment]
but the libnode.so is too big
