### ISSUE TITLE
UnsatisfiedLinkError couldn't find "libJavaScriptCoreWrapper.so"

### ISSUE THREAD

**Issue by aexmachina** [ericwlange/AndroidJSCore#6]
As per your instructions I extracted the tarball into the root of my Android project, but the jar file wasn't being loaded so I moved the contents of the `lib` directory into `app/lib` and this fixed the problem. 

However I now have another error when I try to run my project:

```
12-23 00:03:03.268 3216-3216/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: be.wades.rhinotest, PID: 3216
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/be.wades.rhinotest-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libJavaScriptCoreWrapper.so"
  at java.lang.Runtime.loadLibrary(Runtime.java:366)
  at java.lang.System.loadLibrary(System.java:988)
  at org.liquidplayer.webkit.javascriptcore.JSContext.<clinit>(JSContext.java:205)
  at be.wades.rhinotest.MainActivity.onCreate(MainActivity.java:41)
  at android.app.Activity.performCreate(Activity.java:5990)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
  at android.app.ActivityThread.access$800(ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5257)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

This is a blank new project created with Android Studio 1.5. I've tried moving the directories in `app/lib` into `lib` as well, but this doesn't fix the problem. Any suggestions?

**Comment by aexmachina** [comment]
The solution for me appears to be as follows:

```
app/libs/AndroidJSCoreJNI-1.0.jar
app/src/main/jniLibs/armeabi/libJavaScriptCore.so
app/src/main/jniLibs/armeabi/libJavaScriptCoreWrapper.so
app/src/main/jniLibs/armeabi-v7a/libJavaScriptCore.so
app/src/main/jniLibs/armeabi-v7a/libJavaScriptCoreWrapper.so
app/src/main/jniLibs/mips/libJavaScriptCore.so
app/src/main/jniLibs/mips/libJavaScriptCoreWrapper.so
app/src/main/jniLibs/x86/libJavaScriptCore.so
app/src/main/jniLibs/x86/libJavaScriptCoreWrapper.so
```

**Comment by ericwlange** [comment]
Thanks for the workaround.  I am working on AndroidJSCore 2.0 right now and will make sure it works with Android Studio.

**Comment by ericwlange** [comment]
This issue is resolved with the new release.  Closing.
